CREATE DATABASE NHANVIEN_SESSION4
USE NHANVIEN_SESSION4

CREATE TABLE TRINHDO
(
    MaTD INT IDENTITY(1,1) NOT NULL,
    TenTD NVARCHAR(50) NOT NULL
)

CREATE TABLE CHUCVU
(
    MaChucVu INT NOT NULL,
    TenChucVu VARCHAR(50) NOT NULL,
    TenChucVu_Thua VARCHAR(50) NOT NULL
)

CREATE TABLE NHANVIEN
(
    MaNhanVien INT NOT NULL,
    Hovaten NVARCHAR(MAX) NULL,
    Ngaysinh DATETIME NULL,
    MaTD INT NOT NULL,
    MaChucVu INT NOT NULL
)

ALTER TABLE NHANVIEN
ADD GioiTinh INT DEFAULT 1

ALTER TABLE CHUCVU
ADD CONSTRAINT UQ_CHUCVU_TenChucVu UNIQUE (TenChucVu)

ALTER TABLE TRINHDO
ADD CONSTRAINT PK_TRINHDO PRIMARY KEY (MaTD)

ALTER TABLE CHUCVU
ADD CONSTRAINT PK_CHUCVU PRIMARY KEY (MaChucVu)

ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NHANVIEN PRIMARY KEY (MaNhanVien)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_TRINHDO
FOREIGN KEY (MATD)
REFERENCES TRINHDO(MATD)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_CHUCVU
FOREIGN KEY (MaChucVu)
REFERENCES CHUCVU(MaChucVu)