CREATE DATABASE QL_KINHDOANH
USE QL_KINHDOANH

CREATE TABLE KHACHHANG
(
    MAKHACHHANG VARCHAR(20) NOT NULL,
    TENCONGTY NVARCHAR(50) NOT NULL,
    TENGIAODICH NVARCHAR(50) NOT NULL,
    DIACHI NVARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    DIENTHOAI VARCHAR(15) NOT NULL,
    FAX VARCHAR(15) NOT NULL
)

CREATE TABLE DONDATHANG
(
    SOHOADON VARCHAR(20) NOT NULL,
    MAKHACHHANG VARCHAR(20) NOT NULL,
    MANHANVIEN VARCHAR(20) NOT NULL,
    NGAYDATHANG DATE NOT NULL,
    NGAYGIAOHANG DATE NOT NULL,
    NGAYCHUYENHANG DATE NOT NULL,
    NOIGIAOHANG NVARCHAR(100) NOT NULL
)

CREATE TABLE NHANVIEN
(
    MANHANVIEN VARCHAR(20) NOT NULL,
    HO NVARCHAR(20),
    TEN NVARCHAR(20) NOT NULL,
    NGAYSINH DATE,
    NGAYLAMVIEC DATE NOT NULL,
    DIACHI NVARCHAR(100),
    DIENTHOAI VARCHAR(15) NOT NULL,
    LUONGCOBAN DECIMAL(10,0) NOT NULL,
    PHUCAP DECIMAL(10,0) NOT NULL
)

CREATE TABLE NHACUNGCAP
(
    MACONGTY VARCHAR(20) NOT NULL,
    TENCONGTY NVARCHAR(50) NOT NULL,
    TENGIAODICH NVARCHAR(50) NOT NULL,
    DIACHI NVARCHAR(100) NOT NULL,
    DIENTHOAI VARCHAR(15) NOT NULL,
    FAX VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
)

CREATE TABLE CHITIETDATHANG
(
    SOHOADON VARCHAR(20) NOT NULL,
    MAHANG VARCHAR(20) NOT NULL,
    GIABAN DECIMAL(10,0) NOT NULL,
    SOLUONG INT NOT NULL,
    MUCGIAMGIA DECIMAL(5,2)
)

CREATE TABLE MATHANG
(
    MAHANG VARCHAR(20) NOT NULL,
    TENHANG NVARCHAR(50) NOT NULL,
    MACONGTY VARCHAR(20) NOT NULL,
    MALOAIHANG VARCHAR(20) NOT NULL,
    SOLUONG INT NOT NULL,
    DONVITINH NVARCHAR(20) NOT NULL,
    GIAHANG DECIMAL(10,0) NOT NULL
)

CREATE TABLE LOAIHANG
(
    MALOAIHANG VARCHAR(20) NOT NULL,
    TENLOAIHANG NVARCHAR(50) NOT NULL
)

ALTER TABLE KHACHHANG
ADD CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKHACHHANG)

ALTER TABLE DONDATHANG
ADD CONSTRAINT PK_DONDATHANG PRIMARY KEY (SOHOADON)

ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANHANVIEN)

ALTER TABLE NHACUNGCAP
ADD CONSTRAINT PK_NHACUNGCAP PRIMARY KEY (MACONGTY)

ALTER TABLE CHITIETDATHANG
ADD CONSTRAINT PK_CHITIETDATHANG PRIMARY KEY (SOHOADON,MAHANG)

ALTER TABLE MATHANG
ADD CONSTRAINT PK_MATHANG PRIMARY KEY (MAHANG)

ALTER TABLE LOAIHANG
ADD CONSTRAINT PK_LOAIHANG PRIMARY KEY (MALOAIHANG)

ALTER TABLE DONDATHANG
ADD CONSTRAINT FK_DONDATHANG_KHACHHANG
FOREIGN KEY(MAKHACHHANG)
REFERENCES KHACHHANG(MAKHACHHANG)

ALTER TABLE DONDATHANG
ADD CONSTRAINT FK_DONDATHANG_NHANVIEN
FOREIGN KEY(MANHANVIEN)
REFERENCES NHANVIEN(MANHANVIEN)

ALTER TABLE CHITIETDATHANG
ADD CONSTRAINT FK_CHITIETDATHANG_DONDATHANG
FOREIGN KEY(SOHOADON)
REFERENCES DONDATHANG(SOHOADON)

ALTER TABLE MATHANG
ADD CONSTRAINT FK_MATHANG_NHACUNGCAP
FOREIGN KEY(MACONGTY)
REFERENCES NHACUNGCAP(MACONGTY)

ALTER TABLE CHITIETDATHANG
ADD CONSTRAINT FK_CHITIETDATHANG_MATHANG
FOREIGN KEY(MAHANG)
REFERENCES MATHANG(MAHANG)

ALTER TABLE MATHANG
ADD CONSTRAINT FK_MATHANG_LOAIHANG
FOREIGN KEY(MALOAIHANG)
REFERENCES LOAIHANG(MALOAIHANG)

ALTER TABLE KHACHHANG
DROP COLUMN TENCONGTY

ALTER TABLE KHACHHANG
ADD TENKHACHHANG NVARCHAR(50) NOT NULL,
    TUOI INT NOT NULL

SELECT *
FROM KHACHHANG

SELECT *
FROM KHACHHANG
WHERE DIACHI LIKE N'%Hà Nội%'

SELECT TOP 3
    MAKHACHHANG, TENKHACHHANG, DIACHI, DIENTHOAI
FROM KHACHHANG
ORDER BY MAKHACHHANG

SELECT MAKHACHHANG, TENKHACHHANG, TUOI
FROM KHACHHANG

SELECT MAHANG, TENHANG, SOLUONG * GIAHANG AS TONGTIEN
FROM MATHANG

SELECT *
FROM KHACHHANG
WHERE TENKHACHHANG LIKE N'%Sơn%' OR TENKHACHHANG LIKE N'%Võ%'

SELECT *
FROM KHACHHANG
WHERE TENKHACHHANG LIKE N'%Văn%'

SELECT MAHANG, TENHANG, SOLUONG
FROM MATHANG
WHERE SOLUONG BETWEEN 70 AND 90
ORDER BY SOLUONG DESC

SELECT *
FROM CHITIETDATHANG
WHERE SOHOADON IN ('H01', 'H02', 'H07');

SELECT MAX(GIAHANG) AS GIAHANGMAX, MIN(GIAHANG) AS GIAHANGMIN
FROM MATHANG

SELECT MALOAIHANG, COUNT(MAHANG) AS SOSANPHAM, SUM(SOLUONG) AS TONGSOLUONG
FROM MATHANG
GROUP BY MALOAIHANG;

SELECT MALOAIHANG, COUNT(MAHANG) AS SOSANPHAM, SUM(SOLUONG * GIAHANG) AS TONGTIEN
FROM MATHANG
GROUP BY MALOAIHANG;

SELECT MANHANVIEN, HO + ' ' + TEN AS HOTEN, TUOI, LUONGCOBAN + PHUCAP AS LUONG
FROM NHANVIEN
WHERE NGAYLAMVIEC < '2014-01-01'
ORDER BY LUONG DESC

SELECT *
FROM NHANVIEN
WHERE DAY(NGAYSINH) = 28 AND MONTH(NGAYSINH) = 8;


SELECT SOHOADON, SUM(SOLUONG) AS TONGSOLUONG, SUM(SOLUONG * GIABAN) AS TONGTIEN
FROM CHITIETDATHANG
GROUP BY SOHOADON
HAVING SUM(SOLUONG * GIABAN) > 1000000;

SELECT *
FROM NHACUNGCAP
WHERE DIACHI LIKE N'%Hà Tĩnh%'

SELECT *
FROM NHANVIEN
WHERE PHUCAP + LUONGCOBAN > 10000000