CREATE DATABASE QL_LICHDAY
USE QL_LICHDAY

CREATE TABLE SINHVIEN
(
    MASV CHAR(12) NOT NULL,
    HOTENSV NVARCHAR(50) NOT NULL,
    GIOITINH VARCHAR(3) NOT NULL,
    NGAYSINH DATE NOT NULL,
    QUEQUAN NVARCHAR(100) NOT NULL,
    MALOP CHAR(10) NOT NULL
)

CREATE TABLE LOP
(
    MALOP CHAR(10) NOT NULL,
    TENLOP NVARCHAR(50) NOT NULL,
    MAKHOA CHAR(5) NOT NULL
)

CREATE TABLE KHOA
(
    MAKHOA CHAR(5) NOT NULL,
    TENKHOA NVARCHAR(50) NOT NULL
)

CREATE TABLE MONHOC
(
    MAMH CHAR(5) NOT NULL,
    TENMH NVARCHAR(50) NOT NULL,
    DONVIHT TINYINT NOT NULL
)

CREATE TABLE GIANGVIEN
(
    MAGV CHAR(5) NOT NULL,
    HOTENGV NVARCHAR(50) NOT NULL,
    HOCVI NVARCHAR(20) NOT NULL,
    CHUYENNGANH NVARCHAR(20) NOT NULL,
    NGAYSINH DATE NOT NULL,
    QUEQUAN NVARCHAR(100) NOT NULL,
    GIOITINH CHAR(1) NOT NULL,
    MAKHOA CHAR(5) NOT NULL
)

CREATE TABLE KETQUA
(
    MASV CHAR(12) NOT NULL,
    MAMH CHAR(5) NOT NULL,
    LANTHI TINYINT NOT NULL,
    DIEMTHI TINYINT NOT NULL
)

CREATE TABLE PHANCONG
(
    MALOP CHAR(10) NOT NULL,
    MAMH CHAR(5) NOT NULL,
    MAGV CHAR(5) NOT NULL
)

DELETE KETQUA
WHERE MASV = 'HuyNVph07543'

UPDATE SINHVIEN
SET QUEQUAN = N'Thành Hà Nội', GIOITINH = 'Nam'
WHERE MASV = 'HuyNVph07543'

UPDATE MONHOC
SET TENMH = N'Cơ sở dữ liệu'
WHERE TENMH = N'Tin Văn Phòng'

UPDATE MONHOC
SET DONVIHT = 30
WHERE TENMH = N'Tri Tue Nhan Tao'

UPDATE SINHVIEN
SET HOTENSV = 'Nguyen Thanh Son', GIOITINH = 'Nam'
WHERE HOTENSV = 'Nguyen Thi Lam'

UPDATE SINHVIEN
SET MALOP = 'Pt14353MoB'
WHERE HOTENSV = 'Le Thi Lan Anh'