CREATE DATABASE QLY_NHANSU
USE QLY_NHANSU

CREATE TABLE PHONG_BAN
(
    MA_PB CHAR(5) NOT NULL,
    TEN_NV NVARCHAR(30) NOT NULL,
    MA_TRUONGPHONG INT NOT NULL
);

CREATE TABLE NHAN_VIEN
(
    ID_NHANVIEN INT NOT NULL,
    HO_NV NVARCHAR(30),
    TEN_NV NVARCHAR(30) NOT NULL,
    NAM_SINH SMALLINT,
    DIA_CHI NVARCHAR(50),
    GIOI_TINH CHAR(1) NOT NULL,
    LUONG DECIMAL(8,0),
    PHG CHAR(5) NOT NULL
);

CREATE TABLE QUANLY_DUAN
(
    MA_DUAN INT NOT NULL,
    MA_NHANVIEN INT NOT NULL,
    NGAY_THAM_GIA DATE NOT NULL,
    NGAY_KET_THUC DATE NOT NULL,
    SO_GIO INT,
    VAI_TRO NVARCHAR(30) NOT NULL
);

CREATE TABLE DU_AN
(
    MA_DUAN INT NOT NULL,
    TEN_DUAN NVARCHAR(30) NOT NULL,
    NGAY_BAT_DAU DATE NOT NULL,
    NGAY_KET_THUC DATE NOT NULL
);

ALTER TABLE PHONG_BAN
ADD CONSTRAINT PK_PHONG_BAN PRIMARY KEY (MA_PB)

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT PK_NHANVIEN PRIMARY KEY (ID_NHANVIEN)

ALTER TABLE QUANLY_DUAN
ADD CONSTRAINT PK_QUANLY_DUAN PRIMARY KEY (MA_DUAN,MA_NHANVIEN)

ALTER TABLE DU_AN
ADD CONSTRAINT PK_DUAN PRIMARY KEY (MA_DUAN)

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT FK_NHAN_VIEN_PHONGBAN
FOREIGN KEY(PHG)
REFERENCES PHONG_BAN(MA_PB)

ALTER TABLE QUANLY_DUAN
ADD CONSTRAINT FK_QUANLY_DUAN_NHAN_VIEN
FOREIGN KEY(MA_NHANVIEN)
REFERENCES NHAN_VIEN(ID_NHANVIEN)

ALTER TABLE QUANLY_DUAN
ADD CONSTRAINT FK_QUANLY_DUAN_DU_AN
FOREIGN KEY(MA_DUAN)
REFERENCES DU_AN(MA_DUAN)